### ISSUE TITLE
Don't work cascade delete on H2 DataBase

### ISSUE THREAD

**Issue by BioQwer** [BioQwer/NoteKeeper#16]
![diagram](https://cloud.githubusercontent.com/assets/5636129/6607035/ee248c92-c84c-11e4-9290-f1afe6deb80a.jpg)

```
[00:10:23,760] [DEBUG] org.hibernate.internal.util.EntityPrinter:114 - [Listing entities:]
[00:10:23,761] [DEBUG] org.hibernate.internal.util.EntityPrinter:121 - [com.bioqwer.serverApp.model.User{monitoringsByUserId=[com.bioqwer.serverApp.model.Monitoring#1], password=Passsword1, notesByUserId=[], login=login1, userId=1, email=usqwe@email.ru}]
[00:10:23,761] [DEBUG] org.hibernate.internal.util.EntityPrinter:121 - [com.bioqwer.serverApp.model.Monitoring{noteByNoteId=null, userByUserId=com.bioqwer.serverApp.model.User#1, logData={"userId":1,"email":"usqwe@email.ru","login":"login1","password":"Passsword1"}, id=1, logTime=2015-03-12 00:10:21.716}]
[00:10:23,762] [DEBUG] org.hibernate.SQL:109 - [delete from user where user_id=?]
[00:10:23,766] [DEBUG] org.hibernate.engine.jdbc.spi.SqlExceptionHelper:139 - [could not execute statement [n/a]]
org.h2.jdbc.JdbcSQLException: Нарушение ссылочной целостности: "FK_2E8JL2D67T53XNT9E2CK4IP83: PUBLIC.MONITORING FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(USER_ID) (1)"
Referential integrity constraint violation: "FK_2E8JL2D67T53XNT9E2CK4IP83: PUBLIC.MONITORING FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(USER_ID) (1)"; SQL statement:
delete from user where user_id=? [23503-186]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.get(DbException.java:179)
    at org.h2.message.DbException.get(DbException.java:155)
    at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:426)
    at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:443)
    at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:318)
    at org.h2.table.Table.fireConstraints(Table.java:920)
    at org.h2.table.Table.fireAfterRow(Table.java:938)
    at org.h2.command.dml.Delete.update(Delete.java:100)
    at org.h2.command.CommandContainer.update(CommandContainer.java:78)
    at org.h2.command.Command.executeUpdate(Command.java:254)
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
    at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
    at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3400)
    at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3630)
    at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:114)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
    at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77)
    at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:521)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:122)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy56.delete(Unknown Source)
    at com.bioqwer.serverApp.service.impl.UserServiceImpl.delete(UserServiceImpl.java:36)
    at com.bioqwer.serverApp.integrationTests.NoteServiceTests.tearDown(NoteServiceTests.java:127)
```

**Comment by BioQwer** [comment]
`cascade = CascadeType.REMOVE` say JPA "do cascade delete for Monitoring "

``` Java
@Entity
public class User {

    @JsonIgnore
    private Collection<Monitoring> monitoringsByUserId;

    @OneToMany(mappedBy = "userByUserId", fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
    public Collection<Monitoring> getMonitoringsByUserId() {
        return monitoringsByUserId;
    }

    public void setMonitoringsByUserId(Collection<Monitoring> monitoringsByUserId) {
        this.monitoringsByUserId = monitoringsByUserId;
    }
}

@Entity
public class Monitoring {
    private User userByUserId;

    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "userId", nullable = false)
    public User getUserByUserId() {
        return userByUserId;
    }

    public void setUserByUserId(User userByUserId) {
        this.userByUserId = userByUserId;
    }
}
```
